### ISSUE TITLE
Problème de conflits avec une autre équipe

### ISSUE THREAD

**Issue by Elio-Granger** [CACAO2021/CACAO2021#19]
Bonjour, lorsque je pull du repository général, j'ai un problème de conflits avec les fichiers d'une autre équipe (alors que nous ne les avons pas touchés). Que dois-je faire pour régler le problème ? commit quand même en laissant les erreurs de conflits puis supprimer en local les fichiers en question pour les pull à nouveau depuis l'upstream ensuite ?

@massimotisi 

![image](https://user-images.githubusercontent.com/81296458/113855965-ee175480-97a0-11eb-8682-915db36006fc.png)

**Comment by massimotisi** [comment]
Right click on the eq2Producteur2, Replace with -> Branch, Tag or Reference -> Remote tracking -> select the main repository -> Replace. Then commit all files and push to your repository.

**Comment by Elio-Granger** [comment]
Okay c'est fixé, merci!
